name: Run Sales Portal Orders API tests

on:
    push:
        branches:
            - main
        paths:
            - "src/tests/api/orders/**"
    workflow_dispatch: # Manually trigger the workflow

jobs:
    download-history:
        # if: false
        runs-on: ubuntu-latest
        name: Download history
        steps:
          - name: setup Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.10"
          - run: >
              ARTIFACT_ID=$(curl -L 
              -H "Accept: application/vnd.github+json" 
              -H "X-GitHub-Api-Version: 2022-11-28" 
              "https://github.com/maratgefter/final-boss-aqa-karpovich/actions/artifacts?name=allure-results" 
              | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
              &&
              curl -L 
              -H "Accept: application/vnd.github+json" 
              -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
              -H "X-GitHub-Api-Version: 2022-11-28" 
              https://github.com/maratgefter/final-boss-aqa-karpovich/actions/artifacts/$ARTIFACT_ID/zip 
              -o artifacts.zip &&
              REPORT_ID=$(curl -L 
              -H "Accept: application/vnd.github+json" 
              -H "X-GitHub-Api-Version: 2022-11-28" 
              "https://github.com/maratgefter/final-boss-aqa-karpovich/actions/artifacts?name=github-pages" 
              | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
              &&
              curl -L 
              -H "Accept: application/vnd.github+json" 
              -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
              -H "X-GitHub-Api-Version: 2022-11-28" 
              https://github.com/maratgefter/final-boss-aqa-karpovich/actions/artifacts/$REPORT_ID/zip 
              -o pages.zip
          - run: mkdir allure-results && unzip artifacts.zip -d allure-results
          - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
          - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results
          - name: Store allure history
            uses: actions/upload-artifact@v4
            with:
              name: allure-results
              path:
                allure-results
              retention-days: 1
              
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        needs: download-history
        container:
            image: mcr.microsoft.com/playwright:v1.57.0-noble
        steps:
            # Checkout
            - uses: actions/checkout@v4

            # Install OpenJDK
            - name: Install OpenJDK
              run: |
                  apt-get update
                  apt-get install -y openjdk-17-jre
                  echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

            # Install dependencies
            - name: Install dependencies
              run: npm ci

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            # Run tests
            - name: Run tests
              env:
                  SALES_PORTAL_API_URL: ${{ secrets.SALES_PORTAL_API_URL }}
                  USER_NAME: ${{ secrets.USER_NAME }}
                  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              run: npm run test:api-orders
              continue-on-error: true

            # Create Allure report
            - name: Download all workflow run artifacts
              uses: actions/download-artifact@v4
        
            - name: Create Allure report
              run: npm run allure-report

            - name: Save Allure report
              uses: actions/upload-artifact@v4
              with:
                  name: regression-report
                  path: ./allure-report

            # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              if: success()
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./allure-report
                  destination_dir: allure-report
